export const AUTH_USER = 'AUTH_USER'
export const GET_USER_LIST = 'GET_USER_LIST'
export const LOG_OUT = 'LOG_OUT'

export const LOAD_QUESTIONS = 'LOAD_QUESTIONS'
export const QUESTION_ADDED = 'QUESTION_ADDED'
export const QUESTION_ANSWERED = 'QUESTION_ANSWERED'